### ISSUE TITLE
Test create_campaign function

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#37]
Write end to end unit testing for create_campaign function.

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid Okorie, a Cairo Smart Contract Developer. I can write the unit test for this function by asserting that the campaign was created
I'll like to work on this

**Comment by NueloSE** [comment]
@Oshioke-Salaki I would create suitable test to test state of the contract before and after call covering all edge case for the contract at: [create_campaign](https://github.com/Token-Giver/token-giver/blob/main/contracts/src/campaign.cairo#L56) . kindly assign
