### ISSUE TITLE
Test withdraw function

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#42]
Write end to end tests for the withdrawal function.
NOTE: This issue depends on the completion of issue #41.

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid, a Cairo Smart Contract Developer adept at writing tests
I can work on this issue using an assertion that will involve math concerning the amount withdrawn, and the balance before and after withdrawal

**Comment by Pvsaint** [comment]
Osho please let me handle this issue, I promise to deliver as soon as possible
