### ISSUE TITLE
Fix dependencies conflict

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#49]
Resolve the dependency conflict between @starknet-react/core and starknet packages in the project.

Acceptance Criteria:
The npm install command should execute successfully without any peer dependency conflicts.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

**Comment by Abeeujah** [comment]
Hi, I'd love to work on this, also provide a suggestion to use a more performant package manager `pnpm`

**Comment by Jemiiah** [comment]
Pls can i take this issue ETA : 24 hours
