### ISSUE TITLE
Provide social media inputs

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#57]
update campaign creation form to include inputs for links to users social media or website. (it should be optional)
`twitter(x)`, `youtube`, `website` `github`, `instagram`,`linkedIn` and `telegram`.

**Comment by OWK50GA** [comment]
Hi @Oshioke-Salaki
I'm a Frontend Web Developer with experience using Next.js and I'll like to take this issue as an opportunity to contribute to this amazing product, Token-Giver

**Comment by wheval** [comment]
Can i work on this?

ETA is 1 day.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Kaminar-i** [comment]
Can I take this from here? I am a front end developer and aspiring smart contract developer. This is my will be among my first issues to tackle and i would love to get my hands dirty on this. eta of 5 hours

**Comment by deeseeker** [comment]
Hello, I am Qudus Adeyemi(@deeseeker), a frontend developer with over two years of experience in React,TS,Nextjs and JS.

This is a link to the app I am currently building https://app.myrevva.com/ and this is a project I worked on for a client https://uphoria.io/.

Kindly assign me the task. ETA: less than 24 hrs

**Comment by abdegenius** [comment]
I'd like to take this issue.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a frontend developer with experience in creating dynamic forms and ensuring user-friendly interfaces. I have worked on various projects where I focused on improving user experiences by adding intuitive form fields and maintaining functionality across platforms.

I would love to contribute by updating the campaign creation form to include optional fields for social media and website links such as Twitter (X), YouTube, Website, GitHub, Instagram, LinkedIn, and Telegram. I will ensure these inputs are optional, easy to use, and fit seamlessly into the existing form. Please assign me this task—I’m excited to contribute to the project!

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by SimplementeCao** [comment]
update campaign creation form to include inputs for links to users social media or website. (it should be optional)
twitter(x), youtube, website github, instagram,linkedIn and telegram.

**Comment by jedstroke** [comment]
Mind if I take this issue?

**Comment by caxtonacollins** [comment]
I'd like to take this issue.

**Comment by emarc99** [comment]
Is this issue still available?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Kaminar-i** [comment]
Can I take this from here? I am a front end developer and aspiring smart contract developer. This is my will be among my first issues to tackle and i would love to get my hands dirty on this. eta of 5 hours

**Comment by Oshioke-Salaki** [comment]
gm @Kaminar-i any updates on this?
you have 12 hours to complete this.

**Comment by Akshola00** [comment]
@Oshioke-Salaki thank you for the opportunity 
will start work now
