### ISSUE TITLE
Develop landing page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#60]
Develop the designed landing page and make it responsive for all screen sizes.

This issue depends on #59

**Comment by josephchimebuka** [comment]
Can I take this issue?

**Comment by zintarh** [comment]
Gm, I'm a frontend developer 

I would handle this issue by 
Creating a pixel-perfect and responsive landing page using Tailwind CSS, I would convert the design, i  will apply Tailwind utility classes for layout and styling, and use responsive variants to ensure it adapts seamlessly across all screen sizes.
