### ISSUE TITLE
Replace logos

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#63]
Replace logos on the app using the new brand identity assets here - https://drive.google.com/drive/folders/1P53h48yxAEkLnN9Z90De-ZDJV2CLFWpn?usp=drive_link

**Comment by GoSTEAN** [comment]
May I take care of this?

**Comment by vestor-dev** [comment]
Could I grab this task?

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects

**Comment by ONEONUORA** [comment]
Can i take up this issue. I am a full stack developer. ETA 24  hours

**Comment by abdegenius** [comment]
Is this issue still available?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a frontend developer with experience in  and ensuring consistent design across applications. I have worked on multiple projects where I focused on updating UI elements to reflect the brand's visual guidelines.

I would love to contribute by replacing the logos in the app with the new brand identity assets. With my attention to detail, I will ensure that the updated logos are correctly implemented across all pages and align with the new branding. Please assign me this task—I’m excited to contribute to the project!

**Comment by Prosper1218** [comment]
Hello, I'm prosper. I'm a frontend/Blockchain developer with years of experience. 
If this issue is assigned to me, I'll : 
-Ensure the logo is properly displayed with the perfect width and height.
-Ensure the logo retains perfect sizing on all screens.
This will take me a maximum of 2 days to achieve. 
Assign this issue to me and let me make you happy.

**Comment by MullerTheScientist** [comment]
I'd love to handle this task.

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.
 I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by caxtonacollins** [comment]
Is it okay if I tackle this? this will be my first time contributing.

**Comment by GideonBature** [comment]
Could I be assigned to this?

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will replace the app's logos with the new brand identity assets from the provided link, ensuring they are updated consistently across the application.

**Comment by ussyalfaks** [comment]
Good Afternoon,

I would love to work on this. My name is Usman, and I have solid experience in JavaScript, TypeScript, and React. I'm confident I can contribute effectively to this task. This my portfolio = https://usmanalfaki-1nwv.vercel.app/

**Comment by Awointa** [comment]
May I pick this up?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by Luluameh** [comment]
Let me try this one!
Estimated Completion Time: 1 day

**Comment by akintola4** [comment]
i want to do this ps i can deliver

**Comment by Agbeleshe** [comment]
Can I take care of this issue? I am rontend developer with over 3 years of experience in creating dynamic and reusable UI components. My expertise is ensuring components are functional, visually appealing, and consistent with design systems, including color palettes and accessibility standards.

**Comment by Agbeleshe** [comment]
Can I take care of this issue? I am frontend developer with over 3 years of experience in creating dynamic and reusable UI components. My expertise is ensuring components are functional, visually appealing, and consistent with design systems, including color palettes and accessibility standards.

**Comment by Awointa** [comment]
Thanks I would get to work on this but i would need access to the assets on google drive

**Comment by stephanniegb** [comment]
please join the telegram group
