### ISSUE TITLE
Design Explore page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#64]
Design an explore page using our brand’s color scheme and assets - https://drive.google.com/drive/folders/1P53h48yxAEkLnN9Z90De-ZDJV2CLFWpn?usp=drive_link

NOTE - To be assigned, please drop links to your portfolio or previous works.

**Comment by Joe-joe25** [comment]
Is this issue still available?

**Comment by IrinaBolshagina** [comment]
I have experience in UX/UI design, some of my works in the presentation: https://docs.google.com/presentation/d/1uQiZDmwIHzVob9gTGdDBPbXH_zwtmtC0TB2xySjKB7s/edit?usp=sharing

**Comment by od-hunter** [comment]
May I be assigned to this? This are links to previous designs I've done: https://github.com/mubarak23/chainevents-frontend/issues/6

https://github.com/Peerprotocol/peer-on-strk/issues/8

https://github.com/sivicstudio/starkludo/issues/30

kindly assign me please, I'm up for the task

**Comment by abdegenius** [comment]
Let me try this one!

**Comment by kcmikee** [comment]
My name is Michael, Im a frontend engineer with 5 years of experience , I have experience with react, nextjs and tailwind. Also an alumni of web3bridge. 

I’d like to help with this.

**Comment by Supa-mega** [comment]
I'd love to work on this!

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.
