### ISSUE TITLE
Develop explore page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#65]
Develop the designed explore page and make it responsive for all screen sizes.
This issue is dependent on #64

**Comment by josephchimebuka** [comment]
Is it okay if I tackle this?

**Comment by DanielEmmanuel1** [comment]
Could I take on this issue?

 I'll create the explore page folder with its necessary and add its necessary components needed. I’ll develop the explore page using responsive design techniques with tailwind CSS and make sure it’s optimized for all screen sizes.

I am a first time contributor and would really love the opportunity to work onthis issue.

**Comment by OWK50GA** [comment]
I’d like to work on this.
Could I try solving this?
I'll like to solve it once issue #64 is submitted.

Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.
I would make the screens as dictated by the designs and make them responsive if assigned this issue.

I would make my PR in the earliest time possible

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects

**Comment by vestor-dev** [comment]
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by ONEONUORA** [comment]
Mind if I take this issue? I am a full stack developer , Very good in implementing pixel perfect features. ETA 24 hours

**Comment by Emmanex01** [comment]
Hi,
Can I work on this?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a frontend developer with experience in responsive design and implementing user interfaces based on provided designs. After completing the Cairo Basecamp, I have contributed to several projects, focusing on creating responsive pages that adapt seamlessly across different screen sizes.

I would love to contribute by developing the designed explore page and ensuring it is fully responsive across all screen sizes. I will ensure the layout is optimized for mobile, tablet, and desktop views, maintaining usability and design consistency. Please assign me this task—I’m excited to contribute to the project!

**Comment by deeseeker** [comment]
Hello, I am Qudus Adeyemi(@deeseeker), a frontend developer with over two years of experience in Next JS, CSS, React,TS and JS. I am currently working on social media app for african creators (https://app.myrevva.com/) .

I have deep expertise in crafting responsive, interactive and delivering in time. Let me take on this issue

**Comment by Pvsaint** [comment]
Hi, please let me handle this issue, I'm a front-end and smart contract developer.

**Comment by od-hunter** [comment]
Can I tackle this one Please? I'm an experience ui/ux designer and I'm up for the task. I'll develop the explore page and make it responsive to all screen sizes.

**Comment by MullerTheScientist** [comment]
Can I address this issue, please?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by Awointa** [comment]
I'd love to give this a go.

**Comment by jedstroke** [comment]
May I be assigned to this?

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by jahrulezfrancis** [comment]
I would love to contribute to this. I’ll develop the Explore page as per the design and ensure it’s fully responsive across all screen sizes. Since this task is dependent on issue #64, I’ll make sure everything works smoothly once that is resolved. I can have it shipped in 24 to 36 hours

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
After carefully going through the codebase on GitHub,
- I will write the code to create the Explore Page in the `app/explore/page.tsx` file.
- I will maintain the brand color theme and project structure while creating a sleek explore page
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the design is responsive and works across all devices

## ETA
10 Hours

**Comment by Amarjeet325** [comment]
Could I take over this issue?

**Comment by lindsaymoralesb** [comment]
### About me
Hi! I'm Lindsay, a Software Engineer based in CR, I bring 4.5+ years of exp as a full stack, but I've been specializing as a frontend developer. And since I joined Dojo Coding community I've been immersing myself in the web3 world.
### How would I approach this issue?
First, I'll start by analizing how are current components structured to make sure the new ones stay consistent with the already implemented patterns.
After that I'll start creating the smallest dynamic/reusable components that I would need for this page. Once all this smaller components are implemented, I'll continue with the explore page as its own component, always ensuring that both the small components and the page itself remains responsive on all devices.

**Comment by salazarsebas** [comment]
Hi token-giver,

# My background

I'm Sebastian, software engineer 👨🏻‍💻 and part of the Dojo Coding ⛩️ community, and I would like to contribute to this issue. I have experience with different technologies and I have worked on some projects through OnlyDust and I like to contribute to help the projects.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Develop the exploration page.
- Follow the design standards and any doubt evacuate it with the team.
- Make sure it is fully responsive.
- Perform all the tests and send the pr waiting for feedback.

**Comment by codeZe-us** [comment]
Can I be assigned to this?

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will develop the designed explore page, making it responsive for all devices.
ask questions and communicate with the maintainer.

**Comment by JamesVictor-O** [comment]
I'm a frontend developer with expertise in JavaScript, TypeScript, React.js, and Next.js. With experience in developing visually appealing and responsive web applications, I'm confident in my ability to deliver high-quality work. Eth 2day

**Comment by mimisavage** [comment]
May I take care of this?

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by emarc99** [comment]
I can do this with my UI/UX and FE (ReactJs/NextJS/Tailwind) skills. Awesome to contribute for first time.

**Comment by Pvsaint** [comment]
Hi, I'm Victor,  can I work on this issue? I'm a ffronted and smart contract developer with experience in react js.

**Comment by RareMmemshima** [comment]
Can I take care of this issue?
I'm a frontend and smart contract developer. I have a solid background with react, tailwind, nextjs, javascript, typescript, cairo ETC.  
I will implement this task as expected. 
I'm new to onlydust and i look forward to contributing to this project.

**Comment by Agbeleshe** [comment]
Can I contribute to this one? I am a  frontend developer with over 3 years of experience in creating dynamic and reusable UI components. My expertise are in ensuring components are functional, visually appealing, and consistent with design systems, including color palettes and accessibility standards.

**Comment by Michaelkingsdev** [comment]
I’d like to work on this.

**Comment by suhas-sensei** [comment]
May I be assigned to this? i will develop the designed explore page and make it responsive for all screen sizes and make changes accordingly.

**Comment by deeseeker** [comment]
Thank. I will get to work now
