### ISSUE TITLE
Redesign campaign details page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#66]
Redesign the campaign details page using our brand’s color scheme - https://drive.google.com/drive/folders/1P53h48yxAEkLnN9Z90De-ZDJV2CLFWpn?usp=drive_link

NOTE - To be assigned, please drop links to your portfolio or previous works.

**Comment by Joe-joe25** [comment]
Mind if I try this one?

**Comment by IrinaBolshagina** [comment]
I have experience in UX/UI design, some of my works in the presentation: https://docs.google.com/presentation/d/1uQiZDmwIHzVob9gTGdDBPbXH_zwtmtC0TB2xySjKB7s/edit?usp=sharing

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done

**Comment by DanielEmmanuel1** [comment]
I'd like to take this issue.

I'll start up by creating the ```Campaign-Details``` folder and then start structuring the folder by also creating the necessary components. I’ll start developing the page and making sure it's responsive and optimized for all screen sizes using tailwind CSS

**Comment by vestor-dev** [comment]
Let me try this one!
would love to work on this

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Calebux** [comment]
Can i take this issue up, i have worked on great projects such as starkludo, joyboy and others and i delivered on time and inline with design system.
ETA 2days

**Comment by Calebux** [comment]
I will do justice to this.
I have worked on starkludo, joyboy, starkgolf and chain event 
ETA 2days

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects

**Comment by abdegenius** [comment]
Can I jump on this task?

**Comment by kcmikee** [comment]
My name is Michael, Im a frontend engineer with 5 years of experience , I have experience with react, nextjs and tailwind. Also an alumni of web3bridge. 

I’d like to help with this.

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a frontend developer with experience in creating visually appealing and user-friendly interfaces. I have worked on various projects, focusing on UI/UX design and implementing responsive, brand-consistent designs.

I would love to contribute by redesigning the campaign details page using the brand’s color scheme. With my attention to detail and experience in working with design systems, I can ensure the page aligns with the brand’s identity and provides an enhanced user experience. Please assign me this task—I look forward to contributing to the project!

**Comment by Supa-mega** [comment]
Can I try solving this issue?

**Comment by KVMillz** [comment]
I'm a creative designer and  I'd like to work on this if possible.

**Comment by gidson5** [comment]
Can I contribute to this one? I have worked on the details page for joyboy, worked on Starkludo and also chain events.
I'll deliver this in two days

**Comment by MullerTheScientist** [comment]
I'd love to give this a shot

**Comment by Awointa** [comment]
Can I tackle this one?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Johnalex-hub** [comment]
I am a Senior UI/UX Designer and I will really love to redesign this project. Here is my portfolio  
https://www.figma.com/proto/ZbgShmSUkoVXDF4hBHAxVS/Portfolio-website-Design?page-id=0%3A1&node-id=882-612&node-type=frame&viewport=-810%2C862%2C0.15&t=eE1pZH0m3sbPfesc-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1209%3A309
