### ISSUE TITLE
Implement the redesigned campaign details page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#67]
Implement the redesigned campaign details page and make it responsive for all screen sizes

This issue is dependent on #66

**Comment by josephchimebuka** [comment]
Could I take a shot at this?

**Comment by wheval** [comment]
Hello, I', Wheval. A frontend developer.
I'd love to give this a go. I would ensure a pixel perfect implementation of the Campaign Details page.
This would be my first contribution to Token Giver.
Please assign. Thank You.

ETA is 1 day.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects

**Comment by vestor-dev** [comment]
I’d love to work on this task.

**Comment by Emmanex01** [comment]
Could I take over this issue?

**Comment by abdegenius** [comment]
May I take this issue on?

**Comment by jaykayudo** [comment]
Can i be assigned this issue?
I am a full stack developer with ample experience in building innovative and scalable solutions. on the blockchain side, i bring expertise in DAPP development, smart contract design and integration of several chains technology.

### How i will tackle this
- I will follow the contribution guideline to the letter
- I will implement the redesign as soon as the blocked issue is resolved
- I will open a PR within 2 days prior to the blocked issue resolution

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by aurlic** [comment]
Hey I would be happy to give this a go whenever the issue #66 is done ! I have previously worked on FrontEnd development and would love to be able to improve and perfect my skills working on this project !

**Comment by MullerTheScientist** [comment]
I'd love to take care of this task

**Comment by Awointa** [comment]
I'd love to work on this!

**Comment by caxtonacollins** [comment]
I'd love to give this a go.

**Comment by emarc99** [comment]
May I try my hand at this?
I have both UI/UX and frontend experience, will deliver in 2 days

**Comment by jedstroke** [comment]
I'd love to give this a go.

**Comment by jahrulezfrancis** [comment]
I would really love to contribute to this. I’ll implement the redesigned Campaign Details page and ensure it’s fully responsive across all screen sizes. Since this task is dependent on issue #66, I’ll make sure to address that before proceeding with the implementation. I can have it ready within 24 to 36 hours.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Could I take a shot at this?

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
After carefully going through the codebase on GitHub,
- I will write the code to implement the redesigned Campaign Details Page in the `app/(campaign)/[name]/[address]/[cid]/page.tsx` file.
- I will maintain the brand color theme and project structure
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the design is responsive and works across all devices

## ETA
10 Hours

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by Kaminar-i** [comment]
can i work on this

**Comment by Luluameh** [comment]
Would love to tackle this!
Estimated Completion Time: 2 days

**Comment by lindsaymoralesb** [comment]
### About me
Hi! I'm Lindsay, a Software Engineer based in CR, I bring 4.5+ years of exp as a full stack, but I've been specializing as a frontend developer. And since I joined Dojo Coding community I've been immersing myself in the web3 world.
### How would I approach this issue?
First, I'll start by analizing how are current components structured to make sure the new ones stay consistent with the already implemented patterns.
After that I'll start creating the smallest dynamic/reusable components that I would need for this page. Once all this smaller components are implemented, I'll continue with the campaign details page as its own component, always ensuring that both the small components and the page itself remains responsive on all devices.

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.


making the redesigned campaign responsive for all screens and communicating with the maintainer when working on it.

**Comment by michojekunle** [comment]
Hi, I'm a frontend developer.

I would handle this issue by:

- Implementing the redesigned campaign details page based on the design reference in #66.
- Using Tailwind CSS for styling, applying utility classes for a pixel-perfect and responsive layout.
- Ensuring adaptability across all screen sizes with responsive variants.
- Testing thoroughly to guarantee compatibility and functionality.

### ETA 48 hours

Looking forward to contributing!

**Comment by akintola4** [comment]
i would love to try my hands on this, I promise to deliver before the time given to me

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by RareMmemshima** [comment]
Is it okay if I take this?
I'm a frontend and smart contract developer. I have a solid background with react, tailwind, nextjs, javascript, typescript, cairo ETC.  
I will implement this task as expected. 
I'm new to onlydust and i look forward to contributing to this project.

**Comment by Agbeleshe** [comment]
Let me handle this issue!

**Comment by Michaelkingsdev** [comment]
I’d like to work on this.

**Comment by DanielEmmanuel1** [comment]
I’d love to work on this task.

Good day my name is Deon and I am a Full-Stack web3 developer with ample knowledge  in developing crispy and clean user interfaces. I am a new contributor to this project but I am highly confident i my ability to deliver great results if given the opportunity.

How i hope to solve this issue
I’ll implement the redesigned campaign details page, following every detail like padding, margin and other styling in the figma UI design while ensuring that the page is reponsive across devices.

**Comment by Jethrolopwus** [comment]
Hi, I'm a front end developer with over 3years experience working with javaScript, React.js, next.js and typescript. I can implement the campaign details page and make it responsive on all screen sizes using tailwind css. the ETA for this is 28hrs

**Comment by DanielEmmanuel1** [comment]
Ty, I'll get right on it
