### ISSUE TITLE
Implement Optional Lock Functionality for Campaigns

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver#68]
## Objective:
Enhance the campaign functionality by integrating an optional lock feature using the lock function in the campaign (TBA) contract.

## Input Requirements:
Users should provide the lockUntil time. To simplify input, users will specify the lock time using these fields:  
- Year
- Month
- Day
- Hour (Optional, default to 0 if not provided)
- Minute (Optional, default to 0 if not provided)
- Second (Optional, default to 0 if not provided)
- Timezone.
- Timezone Selection: By default, use  GMT.

Provide a dropdown menu that allows users to select  their local time if needed.
Call the lock function in the campaign contract with the generated Unix timestamp.

Take inspo from 
<img width="685" alt="Screenshot 2024-12-12 at 13 07 50" src="https://github.com/user-attachments/assets/3c4fb5ae-7962-45d2-9a91-e71c8f47dcb0" />

**Comment by josephchimebuka** [comment]
Can I jump on this task?

**Comment by Samuel1-ona** [comment]
i am via @onlydust
Can i take up the issue? i will work on this and give feedback on time

**Comment by Emmanex01** [comment]
I'd be happy to do this.

**Comment by abdegenius** [comment]
Let me try this one!

**Comment by mimisavage** [comment]
Could I take on this issue?

**Comment by Supa-mega** [comment]
Can I start working on this?

**Comment by manlikeHB** [comment]
May I take this issue on?
